---
name: build_document

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

permissions:
  contents: read

env:
  python_version: 3.8

jobs:
  build_document:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{secrets.PUSH_TOKEN}}

      - name: Install dependencies
        run: |
          sudo apt-get install texlive-latex-extra
          sudo apt-get install cm-super
          sudo apt-get install texlive-lang-polish
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install dvipng

      - name: Set up Python ${{env.python_version}}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{env.python_version}}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install matplotlib

      - name: run build script
        working-directory: ${{github.workspace}}
        shell: bash
        run: ./publish.sh

      - name: status at ${{github.ref}}
        run: git status

      - name: commit and push result
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          git config --global user.name 'build_document_action'
          git config --global user.email 'vil02@users.noreply.github.com'
          git add "$(./get_output_folder.sh)"
          git commit -m "Automated document generation"
          git push
...
